### ISSUE TITLE
REQUEST (Feature): If Actor is Invisible, Set to Visible

### ISSUE THREAD

**Issue by crlong02** [kakaroto/fvtt-module-trigger-happy#10]
If you have a hidden actor/token by leveraging the Visibility Toggle, it would be nice if there was a way to automate them becoming visible if something was triggered.

**Comment by kakaroto** [comment]
That's not Trigger Happy's job. With TH, you run a macro when an event happens, you can then have the macro do that. Use Dynamic Effects `toggleVisibility` macro for that.
See this tutorial for example : https://forums.forge-vtt.com/t/trigger-happy-traps/3448
