### ISSUE TITLE
Move token to location on same scene

### ISSUE THREAD

**Issue by dhdodge** [kakaroto/fvtt-module-trigger-happy#11]
Is there a way to move a token a character is using to a different place on the same scene.  For example if they touch a guard they are moved to a jail cell on the same scene.  I know one can do it in a new scene.

**Comment by kakaroto** [comment]
It works the same way whether it's to the same scene or to a different scene.
Refer to this tutorial and post questions there if you have any (this is unrelated to trigger happy itself, as long as the macro is executed as it should, then what the macro does is irrelevant to this module) : https://forums.forge-vtt.com/t/trigger-happy-traps/3448
