### ISSUE TITLE
Not giving invisble players a free ride.

### ISSUE THREAD

**Issue by tposney** [kakaroto/fvtt-module-trigger-happy#13]
I'm now happy with how invisible player characters are behaving and that brings up an issue in trigger happy that invisible players can just waltz across traps and teleports with impunity.

We originally put in a test so that trap tokens would not get grabbed when being dragged across the map. Can we change
```
        if (token.hidden) return true; // don't stop ivnisible tokens?
```
to
```
        if (token.hidden && !game.actors.get(token.actorId)?.isPC) return true; // don't stop ivnisible tokens who aren't PCs?
```

**Comment by kakaroto** [comment]
Not sure. I don't usually like very specific code just to handle a special use case.
What if a character is moving an NPC (beast companion/familiar, or a named NPC they control)? 

The `'dont't stop invisible tokens?` had a question mark to it from the start, so... maybe the answer to that is "no" ? 
How about this instead : don't ignore invisible tokens at all, but instead add a toggle in the token scene controls for GMs only. Like how Furnace has a toggle for token vision, we would have a toggle for activate triggers. Question is.. should it only apply to token/actor triggers or to scene triggers as well... 🤔

**Comment by tposney** [comment]
That was my second option and I like that idea - was looking to keep it
simple. I think it should be all triggers, since that is easy to
understand. - set nothing fires, unsest everything works the same as it
would for players.

**Comment by kakaroto** [comment]
Sounds good to me. That's also what I'd prefer, it's the idea that the toggle is on the token layer's controls that's a bit more annoying, but it's ok 🤷 
I'll implement and push/release soon(TM)

**Comment by kakaroto** [comment]
I hope my choice for an icon is appropriate 🤣
