### ISSUE TITLE
[a request] Trigger pause

### ISSUE THREAD

**Issue by rinnocenti** [kakaroto/fvtt-module-trigger-happy#14]
There could be a trigger to pause the game, something like @Trigger [pause]
So there would be time when something is activated that the narrator knows that someone has triggered  and can narrate something in the meantime

**Comment by kakaroto** [comment]
That's not something that I feel is needed to be part of trigger happy. It makes more sense to have it do `@Macro[pauseGame]` where you'd have a macro that does it (which would be a simple script like `Game.togglePause(true, true)`)
