### ISSUE TITLE
[Issue or Feature Request] Events not triggered when tokens dragged over the area

### ISSUE THREAD

**Issue by VeilOfOblivion** [kakaroto/fvtt-module-trigger-happy#17]
Hi,
Not sure if this is intended. But right now, the events are only triggered when you end your movement in the area. But if you use drag and drop to move a token and don't stop in the marked area, it will not be triggered. Not ideal for traps etc. if they player can just move over it with one big drag and drop :) 
Is this intended?

Thorsten

**Comment by kakaroto** [comment]
Yes, it's intended, read the README file, you need to use the `@Token[capture]` modifier in the line.
See this tutorial for how to set up traps : https://forums.forge-vtt.com/t/trigger-happy-traps/3448
