### ISSUE TITLE
Allow triggers to run GM-authored macros

### ISSUE THREAD

**Issue by crater-git** [kakaroto/fvtt-module-trigger-happy#5]
This was mentioned during the tutorial stream, so figured I'd make a suggestion for it.

Basically how this would work (yours and Tim's words more than mine) is that each macro has an author ID that would be referenced by the trigger. If the macro's author ID doesn't match the one being run by the trigger, the macro won't run with GM permissions.

Additional restrictions might need to be implemented to prevent players from editing GM-created macros, but that might be solved already if the author ID is changed when you save edits.

**Comment by kakaroto** [comment]
Thanks for creating this.
Trigger happy is not really the place to handle it, and Tim has already started implementing it in Dynamic effects. We discussed yesterday after the stream on possible restrictions to make it more secure and i suppose he might have already finished the implementation.
