### ISSUE TITLE
Duplicate Token after teleport

### ISSUE THREAD

**Issue by Elfenduil** [kakaroto/fvtt-module-trigger-happy#7]
Hi,

I create a Teleport trigger who send a token(player) to a Destination teleport.
Each player has his Destination teleport.

When a player touch the Teleport trigger, he sended to his Destination teleport but his token has duplicate to all Destination teleport

For this example, Karnac duplicated to Destination Azog ? why ? Bad code to me ?

![1](https://user-images.githubusercontent.com/65708216/82803492-ec8eb780-9e80-11ea-8c6e-1d4e052efa92.PNG)
![2](https://user-images.githubusercontent.com/65708216/82803505-f31d2f00-9e80-11ea-9836-f3f72bc9fbd0.PNG)
![3](https://user-images.githubusercontent.com/65708216/82803511-f4e6f280-9e80-11ea-9709-0a49821d9d1d.PNG)
![4](https://user-images.githubusercontent.com/65708216/82803518-f7e1e300-9e80-11ea-971c-2dfe16bbf37a.PNG)
![5](https://user-images.githubusercontent.com/65708216/82803987-c0276b00-9e81-11ea-981b-478998a8851b.PNG)
![6](https://user-images.githubusercontent.com/65708216/82803994-c289c500-9e81-11ea-827f-7871db488b31.PNG)

**Comment by kakaroto** [comment]
As long as the macro executes, then Trigger Happy did its job. If the teleport macro isn't working as it should, then it would be a Dynamic Effects issue rather than a Trigger Happy issue.

**Comment by tposney** [comment]
That might not be completely true. If there are multiple trigger happy journals the trigger might be executed multiple times and that would be a trigger happy problem/feature.

I note that there are token refs to the tokens inside the trigger happy journal entries and am not sure what that does.

Could you put console.log() calls inside the macros to see how many times it is being executed?
