### ISSUE TITLE
Map freezing

### ISSUE THREAD

**Issue by WyntherKnight** [kakaroto/fvtt-module-trigger-happy#9]
Using the move script, players teleported to the new scene are unable to move the map by using right mouse botton, Clicking on the scene name on top of the screen fixes this. Is there a way to bypass clicking on the scene name everytime they teleport to a new scene?

**Comment by kakaroto** [comment]
That was a core Foundry bug, but I believe it was fixed in 0.6.1 though I'm not sure. Regarldess, Foundry developer is aware of the issue.

**Comment by WyntherKnight** [comment]
Thanks :D
